# Generated by Django 4.2.20 on 2025-03-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banknote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banknote',
            name='material',
        ),
        migrations.RemoveField(
            model_name='banknote',
            name='mintage',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='mintage',
        ),
        migrations.AddField(
            model_name='banknote',
            name='category',
            field=models.CharField(choices=[('nbu', 'Банкноти НБУ'), ('world', 'Банкноти Країн Світу')], default='nbu', max_length=50),
        ),
        migrations.AddField(
            model_name='coin',
            name='category',
            field=models.CharField(choices=[('nbu_neizilber', 'Монети НБУ з нейзильберу'), ('nbu_silver', 'Срібні монети НБУ'), ('ancient', 'Старовинні монети'), ('investment', 'Інвестиційні монети країн Світу')], default='nbu_neizilber', max_length=50),
        ),
        migrations.AddField(
            model_name='coin',
            name='circulation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='edge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='minting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coins/'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.ImageField(upload_to='coins/'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CoinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coins/multiple/')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.coin')),
            ],
        ),
    ]
