# Generated by Django 4.2.20 on 2025-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_bank_order_city_order_np_office_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
